# Generated by Django 3.1.5 on 2021-01-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=11)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('dummy', models.CharField(blank=True, max_length=200, null=True)),
                ('dummy2', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
